version: 2
jobs:
  checkout_code:
    docker:
      - image: 'circleci/node:latest-browsers'
    working_directory: ~/puppeteer-test
    steps:
      - checkout
      - attach_workspace:
          at: ~/puppeteer-test
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  build:
    docker:
      - image: 'circleci/node:latest-browsers'
    working_directory: ~/puppeteer-test
    steps:
      - attach_workspace:
          at: ~/puppeteer-test
      - run: CI=true yarn test

workflows:
  version: 2
  test_build:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code